eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8084
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  application:
    name: userservice-ws
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://3.19.54.80:3306/mysql
    username: admin
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    #generate-ddl: true

logging:
  level:
    org.springframework: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log