eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8086
spring:
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9090
  application:
    name: discount-ws
