package com.example.discount.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * The Class DiscountEntity.
 */
@DynamoDBTable(tableName = "Discount")
public class DiscountEntity {

	/** The discount id. */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String discountId;

	/** The discount description. */
	@DynamoDBAttribute
	private String discountDescription;

	/** The discount code. */
	@DynamoDBAttribute
	private String discountCode;

	/** The disable discount. */
	@DynamoDBAttribute
	private String disableDiscount;

	/** The discount percentage. */
	@DynamoDBAttribute
	private Double discountPercentage;

	/**
	 * Gets the discount id.
	 *
	 * @return the discount id
	 */
	public String getDiscountId() {
		return discountId;
	}

	/**
	 * Sets the discount id.
	 *
	 * @param discountId the new discount id
	 */
	public void setDiscountId(String discountId) {
		this.discountId = discountId;
	}

	/**
	 * Gets the discount description.
	 *
	 * @return the discount description
	 */
	public String getDiscountDescription() {
		return discountDescription;
	}

	/**
	 * Sets the discount description.
	 *
	 * @param discountDescription the new discount description
	 */
	public void setDiscountDescription(String discountDescription) {
		this.discountDescription = discountDescription;
	}

	/**
	 * Gets the discount code.
	 *
	 * @return the discount code
	 */
	public String getDiscountCode() {
		return discountCode;
	}

	/**
	 * Sets the discount code.
	 *
	 * @param discountCode the new discount code
	 */
	public void setDiscountCode(String discountCode) {
		this.discountCode = discountCode;
	}

	/**
	 * Gets the disable discount.
	 *
	 * @return the disable discount
	 */
	public String getDisableDiscount() {
		return disableDiscount;
	}

	/**
	 * Sets the disable discount.
	 *
	 * @param disableDiscount the new disable discount
	 */
	public void setDisableDiscount(String disableDiscount) {
		this.disableDiscount = disableDiscount;
	}

	/**
	 * Gets the discount percentage.
	 *
	 * @return the discount percentage
	 */
	public Double getDiscountPercentage() {
		return discountPercentage;
	}

	/**
	 * Sets the discount percentage.
	 *
	 * @param discountPercentage the new discount percentage
	 */
	public void setDiscountPercentage(Double discountPercentage) {
		this.discountPercentage = discountPercentage;
	}
}
