eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8010
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  application:
    name: discovery-service
